'''
//////////////////////////////////////////////////////////////////////////////////////////////////////////

412. Fizz Buzz

Given an integer n, return a string array answer (1-indexed) where:

answer[i] == "FizzBuzz" if i is divisible by 3 and 5.
answer[i] == "Fizz" if i is divisible by 3.
answer[i] == "Buzz" if i is divisible by 5.
answer[i] == i if non of the above conditions are true.

//////////////////////////////////////////////////////////////////////////////////////////////////////////

Example:

Input: n = 3
Output: ["1","2","Fizz"]

Input: n = 5
Output: ["1","2","Fizz","4","Buzz"]

Input: n = 15
Output: ["1","2","Fizz","4","Buzz","Fizz","7","8","Fizz","Buzz","11","Fizz","13","14","FizzBuzz"]

//////////////////////////////////////////////////////////////////////////////////////////////////////////
'''

class Solution:
    def fizzBuzz(self, n):
        pass

           
                
            
    
if __name__ == '__main__':

    s = Solution()
    print(s.fizzBuzz(n = 5))       